### ISSUE TITLE
send open commands

### ISSUE THREAD

**Issue by edilhouse** [vigne/node-red-bticino-myhome#2]
hi,
I'm using your node.
you did a good work, i'm not confident in programming.
I didn't understand how to send the command open to my gateway.
Can you help me giving me any example?
thank you very much

**Comment by vigne** [comment]
Hi,

I'm not exactly sure if I understand your question. 

If you want to know how to open/close/stop a shutter:
Set the payload of the message to either "OPEN", "CLOSE", or "STOP" and the topic has to match the topic defined in the node details mask with a preceding "cmd/........".

Here is an example:
[{"id":"805517cd.bb6d28","type":"myhome-cover","z":"600cd9a9.cd896","coverid":"78","topic":"homeautomation/covers/office/window","gateway":"68692c.39b8f6d4","name":"office/window","x":3700,"y":360,"wires":[[]]},{"id":"68069187.963ff","type":"inject","z":"600cd9a9.cd896","name":"","topic":"cmd/homeautomation/covers/office/window","payload":"OPEN","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":3490,"y":320,"wires":[["805517cd.bb6d28"]]},{"id":"3103f678.d9b8fa","type":"inject","z":"600cd9a9.cd896","name":"","topic":"cmd/homeautomation/covers/office/window","payload":"CLOSE","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":3490,"y":360,"wires":[["805517cd.bb6d28"]]},{"id":"a074c97b.9f1358","type":"inject","z":"600cd9a9.cd896","name":"","topic":"cmd/homeautomation/covers/office/window","payload":"STOP","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":3490,"y":400,"wires":[["805517cd.bb6d28"]]},{"id":"68692c.39b8f6d4","type":"myhome-gateway","z":"","name":"F-454","host":"192.168.1.16","port":"20000","timeout":"15"}]

If you want to know, how to connect to your gateway?
You can do this using the "pen" next to the "Gateway" box in the node details mask. Please note that only gateways without password are verified to work (so your NodeRED host needs to be covered by a "trusted" net mask).

Does this answer your question?

Cheers,
Ralph

**Comment by edilhouse** [comment]
thanks for your attention.
Ok, i understand  covers configuration.
Now i have some problems about configuration of lights and switch node; Is it aviable any documents for that?
Thanks again.
Keep in touch
Andrea

my example:
[{"id":"1122e7d9.1fa538","type":"tab","label":"Flow 3","disabled":false,"info":""},{"id":"5edfff7d.a45bc","type":"myhome-light","z":"1122e7d9.1fa538","lightid":"41","topic":"homeautomation/lights/cucina","gateway":"cfb5edb3.a184","name":"cucina","x":410,"y":200,"wires":[[]]},{"id":"6495aa57.6c9484","type":"inject","z":"1122e7d9.1fa538","name":"","topic":"cmd/homeautomation/lights/cucina","payload":"ON","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":210,"y":200,"wires":[["5edfff7d.a45bc"]]},{"id":"1244b051.0babd","type":"inject","z":"1122e7d9.1fa538","name":"","topic":"cmd/homeautomation/lights/cucina","payload":"OFF","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":210,"y":240,"wires":[["5edfff7d.a45bc"]]},{"id":"cfb5edb3.a184","type":"myhome-gateway","z":"","name":"F-454","host":"192.168.1.110","port":"20000","timeout":"60"}]

**Comment by vigne** [comment]
Hello,

apologies for not responding earlier.

Lights expect a JSON which is built to work with Homeassistant default messages.

Long story short, the payload need to be a JSON string with the state attribute, ie. {"state": "ON}.

Here is your example including the described changes:
[{"id":"2f77f40a.aad6dc","type":"myhome-light","z":"2dd73791.6176f8","lightid":"32","topic":"homeautomation/lights/cucina","gateway":"68692c.39b8f6d4","name":"cucina (41)","x":430,"y":200,"wires":[[]]},{"id":"52f3e4f0.24949c","type":"inject","z":"2dd73791.6176f8","name":"","topic":"cmd/homeautomation/lights/cucina","payload":"{\"state\":\"ON\"}","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":230,"y":200,"wires":[["2f77f40a.aad6dc","7814f34c.b45cec"]]},{"id":"bc3dfd83.b7696","type":"inject","z":"2dd73791.6176f8","name":"","topic":"cmd/homeautomation/lights/cucina","payload":"{\"state\":\"OFF\"}","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":240,"y":240,"wires":[["2f77f40a.aad6dc"]]},{"id":"7814f34c.b45cec","type":"debug","z":"2dd73791.6176f8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":340,"y":120,"wires":[]},{"id":"68692c.39b8f6d4","type":"myhome-gateway","z":"","name":"F-454","host":"192.168.1.16","port":"20000","timeout":"15"}]

Also, in case you have a dimmer too, you can use a payload like this to set the brightness: "{"state": "ON", "brightness": 42}"

Cheers,
Ralph
